### ISSUE TITLE
Androidで録音しようとすると落ちる

### ISSUE THREAD

**Issue by rokujyushi** [sdercolin/recstar#1]
Xperia5  
Android11  
version0.4.0  

上記の環境で
ITAコーパスのEMOTION100_072文を録音しようとするとアプリが落ちます。

[有志のOREMO用のテキスト](https://github.com/Haruqa/ita-corpus/blob/main/OREMO%E9%9F%B3%E5%90%8D%E3%83%AA%E3%82%B9%E3%83%88/emotion_transcript_shiftjis.txt)を利用しています。

**Comment by sdercolin** [comment]
```
/storage/emulated/0/Android/data/com.sdercolin.recstar/files/sessions/emotion_transcript_shiftjis 2024-01-06/一つには、西洋人ではない人々が自分たち独自の文化に誇りを持ち始めてきたためと、また一つには、フォークを使わないそれらの地域は最も高い出生率の地域を抱えているという理由から、このことは当たっている。.wav: open failed: ENAMETOOLONG (File name too long)
```

The file name is too long for Android OS. Please edit the reclist to make it shorter.
We can add a fix to restrict the file name that is saved on Android later.

**Comment by rokujyushi** [comment]
読み上げテキストとファイル保存名を分けてインポートすることは可能ですか？   
または省略したファイル名のリストを出力できますか？   
 
Is it possible to import read text and file save names separately?   
Or can you output a list of abbreviated file names?

**Comment by sdercolin** [comment]
次回の更新でOREMO式のCommentを対応しようと思いますが、それでファイル名は音名リスト、読み上げテキストはCommentに、というのはいかがでしょうか。

I plan to support OREMO styled Comment in the next version, so you can put the file names in the reclist, and the texts to read in the comment. What do you think?

**Comment by rokujyushi** [comment]
よろしくお願いします！！！
